CREATE TABLE product_categories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cafeteria_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cafeteria_id) REFERENCES cafeterias(id) ON DELETE CASCADE
);